Models/ErrorViewModel.cs
using System;

namespace C1_1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Formulario.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace C1_1.Models
{

    [Table("afiliado")]
    public class Formulario
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("id")]
        public int id {get;set;}
        
        [Required(ErrorMessage = "Por favor ingrese Nombre")]
        [Display(Name="nombre")]
         [Column("nombre")]
        public String nombre { get; set; }

        [Required(ErrorMessage = "Por favor ingrese Apellido")]
        [Display(Name="apellido")]
         [Column("apellido")]
        public String apellido { get; set; }

            [Display(Name="distrito")]
             [Column("distrito")]
        public String distrito { get; set; }

            [Display(Name="banco")]
             [Column("banco")]
        public String banco { get; set; }
        
            [Display(Name="edad")]
             [Column("edad")]
        public String edad { get; set; }

        [Display(Name="genero")]
         [Column("genero")]
        public String genero { get; set; }

        [Display(Name="autor")]
         [Column("autor")]
        public String autor { get; set; }


        [NotMapped]
        public String Respuesta { get; set; }

    }
}

Controllers/FormularioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using C1_1.Models;
using C1_1.Data;


namespace C1_1.Controllers
{
    public class FormularioController : Controller
    {
        private readonly ILogger<FormularioController> _logger;

        private readonly DatabaseContext _context;

        public FormularioController(ILogger<FormularioController> logger,
            DatabaseContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Formulario()
        {
            return View();
        }
          [HttpPost]
        public IActionResult Registrar(Formulario objFormulario){
            if (ModelState.IsValid)
            {

                _context.Add(objFormulario);
                _context.SaveChanges();
                objFormulario.Respuesta ="= Se registro Correctamente al curso de Alumno ";
            }
            return View("index", objFormulario);
        }

        

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using C1_1.Models;

namespace C1_1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Formulario/Formulario.cshtml
@model C1_1.Models.Formulario;

@{
    ViewData["Title"] = "Formulario Page";
}

<div class="text-center">
    <h1 class="display-4">Hecho por Robert Gutierrez</h1>
    <form asp-controller="Formulario" asp-action="Registrar">
        <hr>
       
    <div class="form-group">
            
            <label>Nombre:</label>
            <input class="form-control" asp-for="nombre"/>
            <br>

            <label>Apellido:</label>
            <input  class="form-control" asp-for="apellido"/>
            <br>
            <label>Distrito:</label>
            <input  class="form-control" asp-for="distrito"/>
            <br>

            <label>Banco</label>
            <select asp-for="banco">
                <option value="BCP">BCP</option>
                <option value="Banco_de_la_nacion">Banco de la nacion</option>
                <option value="Interbank">Interbank</option>
                <option value="Scotiabank">Scotiabank</option>
            </select>
            <br>
            <label>Edad:</label>
            <input  class="form-control" asp-for="edad"/>
            <br>
             <label>Genero:</label>
             <br>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="genero" id="inlineRadio1" value="option1" asp-for="genero">
             <label class="form-check-label" for="inlineRadio1">Masculino</label>
        </div>
        <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="genero" id="inlineRadio1" value="option2" asp-for="genero">
             <label class="form-check-label" for="inlineRadio1">Femenino</label>
        </div>
            <br>
            <label>Autor:</label>
            <input  class="form-control" asp-for="autor"/>
            <br>

            
            <button type="imput" class="btn btn-dark" value="Registrar">Registrar</button>
            <br>
        
    </form>
    <br>
    
    <td>@Html.DisplayNameFor(model => model.Respuesta)</td>
    <td>@Html.DisplayTextFor(model => model.Respuesta)</td>

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - C1_1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">C1_1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Formulario" asp-action="formulario">Formulario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - C1_1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>